#!/usr/bin/env python3
"""okf.py - lightweight tooling for an OKF v0.2 knowledge base.

No external dependencies (Python 3.6+). Subcommands:
  validate        Check every wiki/*.md concept for OKF conformance.
  rebuild-index   Regenerate wiki/index.md from the bundle.
  lint            Heuristic health-check (orphans, broken links, stale, missing type).
  stats           Print a summary of the bundle.

Run from anywhere; it locates the bundle as the parent of this script's dir.
"""
import os
import re
import sys
from datetime import datetime, timezone

# --- locate bundle root (parent of tools/) ---
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIKI = os.path.join(ROOT, "wiki")

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
WIKI_RESERVED = {"index.md", "log.md", "overview.md"}


def now():
    return datetime.now(timezone.utc)


def parse_frontmatter(text):
    """Return (frontmatter_dict, body, ok). Minimal YAML for the small subset OKF uses."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None, text, False
    raw = m.group(1)
    body = text[m.end():]
    data = {}
    # very small YAML parser: handles key: value, nested { by: x, at: y }, lists of - item
    lines = raw.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.strip().startswith("#"):
            i += 1
            continue
        if ":" not in line:
            i += 1
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val == "":
            # possible nested block or list
            if i + 1 < len(lines) and (lines[i + 1].startswith("  -") or lines[i + 1].startswith("    ")):
                # collect indented lines
                block = []
                j = i + 1
                while j < len(lines) and (lines[j].startswith("  ") or lines[j].startswith("\t")):
                    block.append(lines[j].strip())
                    j += 1
                data[key] = "\n".join(block) if block else ""
                i = j
                continue
            else:
                data[key] = ""
                i += 1
                continue
        data[key] = val
        i += 1
    return data, body, True


def iter_concepts():
    """Yield (relpath, abspath, frontmatter, body) for every wiki .md that is a concept."""
    for dirpath, _, files in os.walk(WIKI):
        for fn in sorted(files):
            if not fn.endswith(".md"):
                continue
            ap = os.path.join(dirpath, fn)
            rel = os.path.relpath(ap, WIKI)
            if rel in WIKI_RESERVED:
                continue
            with open(ap, encoding="utf-8") as f:
                text = f.read()
            fm, body, ok = parse_frontmatter(text)
            yield rel, ap, (fm if ok else None), body


def parse_iso(z):
    try:
        return datetime.strptime(z, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except Exception:
        try:
            return datetime.fromisoformat(z.replace("Z", "+00:00"))
        except Exception:
            return None


def cmd_validate():
    errors = 0
    count = 0
    for rel, ap, fm, _ in iter_concepts():
        count += 1
        if fm is None:
            print("MISSING FRONTMATTER: %s" % rel)
            errors += 1
            continue
        if "type" not in fm or not str(fm["type"]).strip():
            print("MISSING type: %s" % rel)
            errors += 1
    print("validate: %d concepts checked, %d error(s)." % (count, errors))
    return 1 if errors else 0


def cmd_stats():
    types = {}
    total = 0
    for rel, ap, fm, _ in iter_concepts():
        total += 1
        t = (fm or {}).get("type", "UNKNOWN")
        types[t] = types.get(t, 0) + 1
    print("Bundle: %s" % WIKI)
    print("Total concepts: %d" % total)
    for t in sorted(types):
        print("  %-18s %d" % (t, types[t]))
    return 0


def cmd_rebuild_index():
    # group by top-level directory
    groups = {}
    roots = []
    for rel, ap, fm, _ in iter_concepts():
        parts = rel.split(os.sep)
        if len(parts) == 1:
            roots.append((rel, fm))
        else:
            top = parts[0]
            groups.setdefault(top, []).append((rel, fm))
    # also gather subdir index entries
    out = ["# Knowledge Base Index", "",
           "> Open Knowledge Format (OKF) v0.2 bundle. See [AGENTS.md](../AGENTS.md) for conventions.",
           "> Regenerated by `tools/okf.py rebuild-index` — run it after changes.",
           ""]
    def entry(rel, fm):
        title = (fm or {}).get("title") or os.path.splitext(os.path.basename(rel))[0]
        desc = (fm or {}).get("description") or ""
        return "* [%s](%s) - %s" % (title, rel, desc)
    if roots:
        out.append("## (root)")
        out.append("")
        for rel, fm in sorted(roots):
            out.append(entry(rel, fm))
        out.append("")
    for g in sorted(groups):
        out.append("## %s" % g.capitalize())
        out.append("")
        for rel, fm in sorted(groups[g]):
            out.append(entry(rel, fm))
        out.append("")
    out.append("## Analyses")
    out.append("")
    out.append("* (pending) - Analyses are written back here when an exploration produces durable insight")
    out.append("")
    with open(os.path.join(WIKI, "index.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("rebuild-index: wrote %s" % os.path.join(WIKI, "index.md"))
    return 0


def cmd_lint():
    problems = 0
    concept_links = {}   # rel -> set of outbound targets
    inbound = {}        # target rel -> count
    all_rels = set()
    fm_cache = {}
    MAX_LINES = 300
    SLUG_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*\.md$")
    for rel, ap, fm, body in iter_concepts():
        all_rels.add(rel)
        fm_cache[rel] = fm or {}
        targets = set()
        for link in LINK_RE.findall(body):
            if link.startswith("http://") or link.startswith("https://") or link.startswith("#"):
                continue
            if link.endswith(".md") or "/.md" in link:
                targets.add(link)
        concept_links[rel] = targets
        for t in targets:
            # normalise relative to bundle root
            norm = t.lstrip("/")
            if norm not in inbound:
                inbound[norm] = 0
            inbound[norm] += 1
    # checks
    for rel, ap, fm, body in iter_concepts():
        if fm is None:
            print("LINT: %s has no frontmatter" % rel); problems += 1; continue
        if not str(fm.get("type", "")).strip():
            print("LINT: %s missing 'type'" % rel); problems += 1
        sa = fm.get("stale_after")
        if sa:
            dt = parse_iso(str(sa))
            if dt and dt <= now():
                print("LINT: %s is stale (stale_after %s)" % (rel, sa)); problems += 1
        # head-first summary rule
        if "## Summary" not in body:
            print("LINT: %s missing '## Summary' section (head-first rule)" % rel); problems += 1
        else:
            idx = body.find("## Summary")
            nxt = body.find("##", idx + 12)
            section = body[idx + 12: nxt if nxt != -1 else len(body)]
            if len(section.strip()) < 40:
                print("LINT: %s '## Summary' is too short (<40 chars)" % rel); problems += 1
        # page length cap
        nlines = body.count("\n") + 1
        if nlines > MAX_LINES:
            print("LINT: %s is %d lines (> %d) — split it" % (rel, nlines, MAX_LINES)); problems += 1
        # filename slug rule
        base = os.path.basename(rel)
        if not SLUG_RE.match(base):
            print("LINT: %s bad filename (use kebab-case ASCII slug, no dates/spaces)" % rel); problems += 1
    # broken links
    for rel, targets in concept_links.items():
        for t in targets:
            norm = t.lstrip("/")
            # strip anchor
            norm = norm.split("#")[0]
            if norm and norm not in all_rels:
                print("LINT: %s -> broken link %s" % (rel, t)); problems += 1
    # orphans (no inbound, not in a reserved/index)
    for rel in all_rels:
        if inbound.get(rel, 0) == 0 and rel not in {"overview.md"}:
            # overview is the landing page; allow it. warn only for deeper orphans.
            if "/" in rel:
                print("LINT: %s is an orphan (no inbound links)" % rel); problems += 1
    print("lint: %d problem(s) found." % problems)
    return 1 if problems else 0


def _contradiction_issues():
    """Return (warnings, errors) for type: Contradiction pages.

    Checks:
      - resolution: resolved but no resolved_by
      - fewer than 2 claims entries
      - open past stale_after
      - pages with inline '## Contradictions' entries still marked stable
    """
    warnings, errors = [], []
    INLINE_RE = re.compile(r"status:\s*open\b", re.I)
    for rel, ap, fm, body in iter_concepts():
        if fm is None:
            continue
        ftype = str(fm.get("type", "")).strip().lower()
        raw_fm = _raw_frontmatter(ap)

        if ftype == "contradiction":
            # count entries under 'claims:' only — 'sources:' uses the same
            # '- id:' shape and would otherwise inflate the count.
            m_claims = re.search(r"^claims:\s*\n((?:^[ \t]+.*\n?)*)", raw_fm, re.M)
            claims_block = m_claims.group(1) if m_claims else ""
            claims = re.findall(r"^\s*-\s+id:\s*\S+", claims_block, re.M)
            if len(claims) < 2:
                errors.append("%s is a Contradiction with %d claims (need >= 2)"
                              % (rel, len(claims)))
            res = str(fm.get("resolution", "")).strip().lower()
            if res == "resolved" and not str(fm.get("resolved_by", "")).strip():
                errors.append("%s is resolved but has no 'resolved_by'" % rel)
            if res not in ("open", "resolved"):
                errors.append("%s has invalid resolution %r (want open|resolved)"
                              % (rel, res))
            elif res == "open":
                sa = fm.get("stale_after")
                dt = parse_iso(str(sa)) if sa else None
                if dt and dt <= now():
                    warnings.append("%s is an OPEN contradiction past stale_after (%s)"
                                    % (rel, sa))
        else:
            # inline contradictions on ordinary pages
            if "## Contradictions" in body and INLINE_RE.search(body):
                if str(fm.get("status", "stable")).strip().lower() != "draft":
                    errors.append(
                        "%s has an open inline contradiction but status is not draft" % rel)
    return warnings, errors


def _raw_frontmatter(ap):
    """Return the raw frontmatter text (for list counting the mini-YAML can't do)."""
    with open(ap, encoding="utf-8") as f:
        text = f.read()
    m = FRONTMATTER_RE.match(text)
    return m.group(1) if m else ""


def cmd_contradictions():
    """List all open contradictions in the bundle."""
    open_items, resolved_items = [], []
    for rel, ap, fm, body in iter_concepts():
        if fm is None:
            continue
        ftype = str(fm.get("type", "")).strip().lower()
        if ftype == "contradiction":
            res = str(fm.get("resolution", "open")).strip().lower()
            title = fm.get("title") or os.path.splitext(os.path.basename(rel))[0]
            line = "  %-55s %s" % (title, res)
            (open_items if res != "resolved" else resolved_items).append(line)
    print("Open contradictions:")
    print("\n".join(open_items) if open_items else "  (none)")
    print("")
    print("Resolved contradictions: %d" % len(resolved_items))
    for line in resolved_items:
        print(line)
    return 0


def main(argv):
    if not os.path.isdir(WIKI):
        print("ERROR: wiki/ not found at %s" % WIKI)
        return 2
    cmd = argv[1] if len(argv) > 1 else "stats"
    if cmd == "validate":
        return cmd_validate()
    if cmd == "stats":
        return cmd_stats()
    if cmd == "rebuild-index":
        return cmd_rebuild_index()
    if cmd == "lint":
        rc = cmd_lint()
        warns, errs = _contradiction_issues()
        for w in warns:
            print("LINT: %s" % w)
        for e in errs:
            print("LINT: %s" % e)
        total = len(warns) + len(errs)
        if total:
            print("lint: %d contradiction issue(s) found." % total)
        return 1 if (rc or errs) else 0
    if cmd == "contradictions":
        return cmd_contradictions()
    print("unknown command: %s" % cmd)
    print("usage: okf.py [validate|stats|rebuild-index|lint|contradictions]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
